site_name: DevTeam SIIS Ltd Docs
site_url: siisltdmigrations.rtfd.io
site_description: SIISLtd.Migrations
site_author: SIIS Ltd
copyright: SIIS Ltd Â© 2019

nav:
  - 'Intro' : 'index.md'
  - 'Quick Start': 'quickstart.md'
  - 'Features': 'features.md'
  - 'Versioning': 'verisoning.md'
  - 'Usage': 'usage.md'


theme:
  name: 'material'
  language: 'ru'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  palette:
    primary: 'red'
    accent: 'red'

markdown_extensions:
  - codehilite
  - markdown_include.include:
      base_path: docs

