site_name: Curiosity.Migrations Documentation
site_url: https://curiosity-migrations.readthedocs.io
site_description: Curiosity.Migrations - Database migration framework for .NET and .NET Core
site_author: SIIS Ltd | Markeli
copyright: <a href="https://survey-studio.com">SIIS Ltd | Markeli</a> Â© 2025

nav:
  - 'Intro': index.md
  - 'Quick Start': quickstart.md
  - 'The Philosophy Behind Curiosity.Migrations': philosophy.md
  - 'Basics': basics.md
  - 'Supported Databaes': supported_databases.md
  - 'Features':
    - 'Script Migration':
      - 'What is it': features/script_migration/index.md
      - 'Batches': features/script_migration/batches.md
    - 'Code Migration':
      - 'What is it': features/code_migration/index.md
      - 'EntityFramework Integration': features/code_migration/ef_integration.md
      - 'Dependency Injection': features/code_migration/di.md
    - 'Migration Providers': features/migration_providers.md
    - 'Variables': features/variables.md
    - 'Transactions': features/transactions.md
    - 'Pre-migrations': features/pre_migrations.md
    - 'Logging': features/logging.md
    - 'Journal': features/journal.md
    - 'Downgrade': features/downgrade.md
    - 'Dependencies': features/dependencies.md
    - 'Curiosity.Migration': changelog/curiosity.migration.md
    - 'Curiosity.Migration.PostgreSQL': changelog/curiosity.migration.postgres.md

theme:
  name: material
  language: en
  favicon: images/siisltd.png
  logo: images/dark_siisltd.png
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: red
    accent: red
  features:
    - navigation.sections
    - navigation.expand

markdown_extensions:
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
      base_path: docs


extra_css:
  - 'stylesheets/extra.css'
